# Generated by Django 5.1.4 on 2025-03-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fathers_occupation', models.CharField(max_length=255)),
                ('caste_category', models.CharField(choices=[('General', 'General'), ('OBC', 'Other Backward Class (OBC)'), ('SC', 'Scheduled Caste (SC)'), ('ST', 'Scheduled Tribe (ST)'), ('NT', 'Nomadic Tribes (NT)'), ('VJNT', 'Vimukta Jati Nomadic Tribes (VJNT)'), ('EWS', 'Economically Weaker Section (EWS)'), ('SBC', 'Special Backward Class (SBC)')], max_length=20)),
                ('college_name', models.CharField(default='Pimpri Chinchwad College of Engineering Nigdi, Pune', max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('prn_number', models.CharField(max_length=20, unique=True)),
                ('photo', models.FileField(upload_to='scheme_documents/photos/')),
                ('application_form', models.FileField(upload_to='scheme_documents/forms/')),
                ('income_certificate', models.FileField(upload_to='scheme_documents/certificates/')),
                ('caste_certificate', models.FileField(blank=True, null=True, upload_to='scheme_documents/certificates/')),
                ('last_year_marksheet', models.FileField(upload_to='scheme_documents/marksheets/')),
                ('domicile_certificate', models.FileField(upload_to='scheme_documents/certificates/')),
                ('admission_receipt', models.FileField(upload_to='scheme_documents/receipts/')),
                ('aadhar_card', models.FileField(upload_to='scheme_documents/identity/')),
                ('bank_passbook', models.FileField(upload_to='scheme_documents/passbooks/')),
                ('caste_validity_certificate', models.FileField(blank=True, null=True, upload_to='scheme_documents/certificates/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('hours_worked', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
