# Generated by Django 5.1.4 on 2025-03-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemeapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Correction Required', 'Correction Required')], default='Pending', max_length=20),
        ),
    ]
