# Generated by Django 5.1.4 on 2025-03-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0003_alter_schemeapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemeapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Correction Required', 'Correction Required'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
