# Generated by Django 4.2.7 on 2025-09-28 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import scheme.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheme', '0004_alter_schemeapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worklog',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worklog',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schemeapplication',
            name='aadhar_card',
            field=models.FileField(upload_to='scheme_documents/identity/', validators=[scheme.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='schemeapplication',
            name='admission_receipt',
            field=models.FileField(upload_to='scheme_documents/receipts/', validators=[scheme.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='schemeapplication',
            name='application_form',
            field=models.FileField(upload_to='scheme_documents/forms/', validators=[scheme.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='schemeapplication',
            name='bank_passbook',
            field=models.FileField(upload_to='scheme_documents/passbooks/', validators=[scheme.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='schemeapplication',
            name='caste_certificate',
            field=models.FileField(blank=True, null=True, upload_to='scheme_documents/certificates/', validators=[scheme.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='schemeapplication',
            name='caste_validity_certificate',
            field=models.FileField(blank=True, null=True, upload_to='scheme_documents/certificates/', validators=[scheme.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='schemeapplication',
            name='domicile_certificate',
            field=models.FileField(upload_to='scheme_documents/certificates/', validators=[scheme.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='schemeapplication',
            name='income_certificate',
            field=models.FileField(upload_to='scheme_documents/certificates/', validators=[scheme.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='schemeapplication',
            name='last_year_marksheet',
            field=models.FileField(upload_to='scheme_documents/marksheets/', validators=[scheme.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='schemeapplication',
            name='photo',
            field=models.FileField(upload_to='scheme_documents/photos/', validators=[scheme.models.validate_image_file]),
        ),
        migrations.AlterUniqueTogether(
            name='worklog',
            unique_together={('student', 'date')},
        ),
    ]
