# Generated by Django 4.2.7 on 2025-09-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0006_department_studentdepartmentassignment_and_more'),
    ]

    operations = [
    ]
