# Generated by Django 4.2.7 on 2025-10-08 08:19

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheme', '0007_auto_20250928_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_hour', models.DecimalField(decimal_places=2, help_text='Payment rate per hour in INR', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('effective_from', models.DateField(help_text='Date from which this rate becomes effective')),
                ('effective_until', models.DateField(blank=True, help_text='Date until which this rate is effective (leave blank for ongoing)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this rate change', null=True)),
                ('set_by', models.ForeignKey(limit_choices_to={'role': 'el_coordinator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_rates_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Rate',
                'verbose_name_plural': 'Payment Rates',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('student', 'Individual Student'), ('department', 'Department Report'), ('all_departments', 'All Departments'), ('monthly_summary', 'Monthly Summary')], max_length=20)),
                ('export_month', models.DateField(help_text='Month for which export was generated')),
                ('file_name', models.CharField(help_text='Generated file name', max_length=255)),
                ('file_path', models.CharField(help_text='Path to the exported file', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, to='scheme.department')),
                ('exported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_exports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, help_text='Student (if applicable)', limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Export',
                'verbose_name_plural': 'Payment Exports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_month', models.DateField(help_text='Month for which payment is calculated (stored as first day of month)')),
                ('total_hours', models.DecimalField(decimal_places=2, help_text='Total verified hours for the month', max_digits=6)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, help_text='Rate per hour used for calculation', max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total calculated amount (hours × rate)', max_digits=10)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('approved', 'Approved'), ('processed', 'Processed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='calculated', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['el_coordinator', 'department_encharge']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL)),
                ('calculated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_payments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='scheme.department')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Records',
                'ordering': ['-payment_month', 'student__first_name'],
                'unique_together': {('student', 'payment_month')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentPaymentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_month', models.DateField(help_text='Month for which summary is calculated')),
                ('total_students', models.PositiveIntegerField(help_text='Number of students who worked')),
                ('total_hours', models.DecimalField(decimal_places=2, help_text='Total verified hours for all students', max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total payment amount for the department', max_digits=12)),
                ('average_hours_per_student', models.DecimalField(decimal_places=2, help_text='Average hours worked per student', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_summaries', to='scheme.department')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department Payment Summary',
                'verbose_name_plural': 'Department Payment Summaries',
                'ordering': ['-payment_month', 'department__name'],
                'unique_together': {('department', 'payment_month')},
            },
        ),
    ]
