# Generated by Django 4.2.7 on 2025-10-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0008_paymentrate_paymentexport_paymentrecord_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrate',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Payment Rate', 'verbose_name_plural': 'Payment Rate'},
        ),
        migrations.RemoveField(
            model_name='paymentrate',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='paymentrate',
            name='effective_until',
        ),
        migrations.RemoveField(
            model_name='paymentrate',
            name='is_active',
        ),
    ]
