# Generated by Django 4.2.7 on 2025-10-17 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheme', '0009_simplify_payment_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_month', models.DateField(help_text='Month for which payment is calculated (stored as first day of month)')),
                ('total_hours', models.DecimalField(decimal_places=2, help_text='Total verified hours for the month', max_digits=6)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, help_text='Rate per hour used for calculation', max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total calculated amount (hours × rate)', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the calculation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_calculations_made', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_calculations', to='scheme.department')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Calculation',
                'verbose_name_plural': 'Payment Calculations',
                'ordering': ['-calculation_month', 'student__first_name'],
                'unique_together': {('student', 'calculation_month')},
            },
        ),
        migrations.AlterModelOptions(
            name='departmentpaymentsummary',
            options={'ordering': ['-calculation_month', 'department__name'], 'verbose_name': 'Department Calculation Summary', 'verbose_name_plural': 'Department Calculation Summaries'},
        ),
        migrations.RenameField(
            model_name='departmentpaymentsummary',
            old_name='payment_month',
            new_name='calculation_month',
        ),
        migrations.AlterUniqueTogether(
            name='departmentpaymentsummary',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='departmentpaymentsummary',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_summaries', to='scheme.department'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentpaymentsummary',
            unique_together={('department', 'calculation_month')},
        ),
        migrations.DeleteModel(
            name='PaymentRecord',
        ),
    ]
