# Generated by Django 4.2.7 on 2025-10-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0010_convert_payment_record_to_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeapplication',
            name='comments',
            field=models.TextField(blank=True, help_text='General comments and field-specific feedback', null=True),
        ),
    ]
